### ISSUE TITLE
Здаров. Мож описать подсказать как и насколко это работает? 

### ISSUE THREAD

**Issue by Sharabaddin** [bpteam/find-good-exchange#1]
Делаю нечто подобное.
Пробовал запустить неполучилось.

**Comment by bpteam** [comment]
У меня получилось, только профита нет. при лучшем обмене выходишь в 0. То есть грубо говоря доход 1.6% от суммы, но из-за комиссии в 0.8% за один обмен доход уходит в Webmoney. Вот такие пироги.

**Comment by Sharabaddin** [comment]
Мож скайп свой дать.
